"""empty message

Revision ID: acb7fc47cd27
Revises: None
Create Date: 2016-02-07 00:37:43.122232

"""

# revision identifiers, used by Alembic.
revision = 'acb7fc47cd27'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_name'), 'scores', ['name'], unique=False)
    op.create_index(op.f('ix_scores_score'), 'scores', ['score'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_name'), table_name='scores')
    op.drop_table('scores')
    ### end Alembic commands ###
